export const GET_CLIENTS = 'GET_CLIENTS';
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS';
export const GET_CLIENTS_FAILURE = 'GET_CLIENTS_FAILURE';
export const GET_CLIENTS_CANCELLED = 'GET_CLIENTS_CANCELLED';

export const CREATE_CLIENT = 'CREATE_CLIENT';
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS';
export const CREATE_CLIENT_FAILURE = 'CREATE_CLIENT_FAILURE';
export const CREATE_CLIENT_CANCELLED = 'CREATE_CLIENT_CANCELLED';

export const REMOVE_CLIENT = 'REMOVE_CLIENT';
export const REMOVE_CLIENT_SUCCESS = 'REMOVE_CLIENT_SUCCESS';
export const REMOVE_CLIENT_FAILURE = 'REMOVE_CLIENT_FAILURE';
export const REMOVE_CLIENT_CANCELLED = 'REMOVE_CLIENT_CANCELLED';

export const EDIT_CLIENT = 'EDIT_CLIENT';
export const EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS';
export const EDIT_CLIENT_FAILURE = 'EDIT_CLIENT_FAILURE';
export const EDIT_CLIENT_CANCELLED = 'EDIT_CLIENT_CANCELLED';

export const SEARCH_CLIENT = 'SEARCH_CLIENT';
export const SEARCH_CLIENT_SUCCESS = 'SEARCH_CLIENT_SUCCESS';
export const SEARCH_CLIENT_FAILURE = 'SEARCH_CLIENT_FAILURE';
export const SEARCH_CLIENT_CANCELLED = 'SEARCH_CLIENT_CANCELLED';